fix: comment out rollback steps in deploy workflow for clarity

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -93,65 +93,62 @@ jobs:
             git push origin $NEW_TAG
 
 
-  rollback:
-    name: Rollback to last stable version
-    if: failure()  # Запускаем откат, если deploy упал
-    runs-on: ubuntu-latest
-    needs: deploy  # Ждем завершения deploy
+  # rollback:
+  #   name: Rollback to last stable version
+  #   if: failure()  # Запускаем откат, если deploy упал
+  #   runs-on: ubuntu-latest
+  #   needs: deploy  # Ждем завершения deploy
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Get last 2 release tags
-        id: get_tags
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST  }}
-          username: ${{ secrets.SSH_USER  }}
-          key: ${{ secrets.SSH_KEY }}
-          port: ${{ secrets.SSH_PORT }}
-          script: |
-            # Получаем два последних релиза
-            cd /root/ChatGPT_Telegram_Bot
-            git checkout prod
-            TAGS=($(git tag --sort=-creatordate | head -2))
-            echo "LATEST_TAG=${TAGS[0]}" >> $GITHUB_ENV
-            echo "PREV_TAG=${TAGS[1]}" >> $GITHUB_ENV
+  #     - name: Get last 2 release tags
+  #       id: get_tags
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.SSH_HOST  }}
+  #         username: ${{ secrets.SSH_USER  }}
+  #         key: ${{ secrets.SSH_KEY }}
+  #         port: ${{ secrets.SSH_PORT }}
+  #         script: |
+  #           # Получаем два последних релиза
+  #           cd /root/ChatGPT_Telegram_Bot
+  #           git checkout prod
+  #           TAGS=($(git tag --sort=-creatordate | head -2))
+  #           echo "LATEST_TAG=${TAGS[0]}" >> $GITHUB_ENV
+  #           echo "PREV_TAG=${TAGS[1]}" >> $GITHUB_ENV
 
-      - name: Revert to previous release
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST  }}
-          username: ${{ secrets.SSH_USER  }}
-          key: ${{ secrets.SSH_KEY }}
-          port: ${{ secrets.SSH_PORT }}
-          script: |
-            cd /root/ChatGPT_Telegram_Bot
-            git checkout prod
-            git revert -m 1 --no-edit HEAD
-            git commit --amend -m "Release $PREV_TAG (Revert $LATEST_TAG) [skip ci]"
-            git push origin prod
+  #     - name: Revert to previous release
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.SSH_HOST  }}
+  #         username: ${{ secrets.SSH_USER  }}
+  #         key: ${{ secrets.SSH_KEY }}
+  #         port: ${{ secrets.SSH_PORT }}
+  #         script: |
+  #           cd /root/ChatGPT_Telegram_Bot
+            
 
-      - name: Restart Docker Compose on Server
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST  }}
-          username: ${{ secrets.SSH_USER  }}
-          key: ${{ secrets.SSH_KEY }}
-          port: ${{ secrets.SSH_PORT }}
-          script: |
-            set -e  # Остановка при ошибке
-            cd /root/ChatGPT_Telegram_Bot
-            git checkout prod
+  #     - name: Restart Docker Compose on Server
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.SSH_HOST  }}
+  #         username: ${{ secrets.SSH_USER  }}
+  #         key: ${{ secrets.SSH_KEY }}
+  #         port: ${{ secrets.SSH_PORT }}
+  #         script: |
+  #           set -e  # Остановка при ошибке
+  #           cd /root/ChatGPT_Telegram_Bot
+  #           git checkout prod
 
-            echo "Pulling latest stable commit from prod"
-            git pull origin prod  # Обновляем код после отката
+  #           echo "Pulling latest stable commit from prod"
+  #           git pull origin prod  # Обновляем код после отката
 
-            echo "Stopping running containers"
-            docker compose down
+  #           echo "Stopping running containers"
+  #           docker compose down
 
-            echo "Rebuilding and restarting services"
-            docker compose build  # Пересобираем (если Dockerfile изменился)
-            docker compose up -d   # Запускаем заново
+  #           echo "Rebuilding and restarting services"
+  #           docker compose build  # Пересобираем (если Dockerfile изменился)
+  #           docker compose up -d   # Запускаем заново
       
